#!/bin/bash
# cloud-init: generated by Terraform — do not edit directly.
set -euo pipefail

# ── Environment (injected by Terraform at plan time) ──────────────────────────
export VPN_SUBNET="${vpn_subnet}"
export LETSENCRYPT_EMAIL="${letsencrypt_email}"

# ── Clone repo and run bootstrap ──────────────────────────────────────────────
apt-get update -qq && apt-get install -y -qq git
git clone ${repo_url} /root/infrastructure
cd /root/infrastructure
bash setup/init.sh
